on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #   push:
  #     branches: ["main"]
  #   pull_request:
  #     branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 SSH-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 💻 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔨 Build Project
        run: npm run production

      - name: 📂 Sync files
        # https://github.com/SamKirkland/web-deploy
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_SERVER }}
          remote-user: ${{ secrets.SSH_USERNAME }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: 22
          destination-path: ./www/public_html/
          rsync-options: >
            --dry-run
            --archive
            --verbose
            --compress
            --delete-after
            --human-readable
            --exclude-from=.github/workflows/deploy/exlude-files.txt
